export function generateEmployeeData(branch: string, role: string) {
  const ts = Date.now() + Math.floor(Math.random() * 1000);

  return {
    branch,
    role,
    name: `AutoEmp_${role}_${ts}`,
    mobile: `9${Math.floor(100000000 + Math.random() * 900000000)}`,
    email: `auto${role}${ts}@test.com`,
    dailySalary: "0",
    monthlySalary: "0",
    password: process.env.EMP_DEFAULT_PASSWORD || "Test@123",
  };
}

export function generateCustomerData() {
  const customerNames = [
    "Ram",
    "Martin",
    "John",
    "Sarah",
    "David",
    "Emma",
    "Michael",
    "Lisa",
    "James",
    "Anna",
    "Robert",
    "Maria",
    "William",
    "Jennifer",
    "Charles",
    "Elizabeth",
    "Thomas",
    "Linda",
    "Daniel",
    "Patricia",
    "Matthew",
    "Susan",
    "Anthony",
    "Jessica",
    "Mark",
    "Nancy",
    "Donald",
    "Betty",
    "Steven",
    "Helen",
    "Paul",
    "Sandra",
    "Andrew",
    "Donna",
    "Kenneth",
    "Carol",
    "Joshua",
    "Ruth",
    "Kevin",
    "Sharon",
    "Brian",
    "Michelle",
    "George",
    "Laura",
    "Edward",
    "Emily",
    "Ronald",
    "Kimberly",
    "Timothy",
    "Deborah",
    "Ravi",
    "Priya",
    "Amit",
    "Kavya",
    "Rajesh",
    "Pooja",
    "Suresh",
    "Meera",
    "Vikram",
    "Anjali",
  ];

  const randomName =
    customerNames[Math.floor(Math.random() * customerNames.length)];

  return {
    name: randomName,
    mobile: `9${Math.floor(100000000 + Math.random() * 900000000)}`,
    created_at: new Date().toISOString(),
    fields_filled: ["name", "mobile"],
    mandatory_only: true,
  };
}
